<?php


namespace app\controller;


use app\BaseController;
use tauthz\facade\Enforcer;

class Order extends BaseController
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $g = input('g', '', 'trim');
        if (!$g) {
            dd('Not logged in, unable to access!!');
        }

        // 校验权限
        $c = strtolower(request()->controller());
        $a = strtolower(request()->action());
        if (!Enforcer::enforce($g, $c, $a)) {
            $resp = response()->data('Unauthorized.')->code(403);
            dd($resp->getData());
        }
    }

    public function list()
    {
        return 'OK';
    }

    public function get()
    {
        return 'OK';
    }

    public function import()
    {
        return 'OK';
    }

    public function export()
    {
        return 'OK';
    }

}